name: vr-therapy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9011921649798751
title: VR Therapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.625
  lightness: 0.22190380631946027
  saturation: 0.8956394752021879
  rhythmicContrast: 0.2678349828347564
purpose: []
